// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLUmnwyCdvrIsyOW7Kzh_976iwBXjLR0A',
    appId: '1:937453068234:web:1984f8a7f178a1ee02f933',
    messagingSenderId: '937453068234',
    projectId: 'finance-app-7ceb3',
    authDomain: 'finance-app-7ceb3.firebaseapp.com',
    storageBucket: 'finance-app-7ceb3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7sITo5c-7Qlu0YLdZ8LlTbMStAcztdrc',
    appId: '1:937453068234:android:8012e27e7f1ee6e802f933',
    messagingSenderId: '937453068234',
    projectId: 'finance-app-7ceb3',
    storageBucket: 'finance-app-7ceb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA05x1rgwqr2rtSVryJOX_4B1fqXrtS5wI',
    appId: '1:937453068234:ios:ef691de77e28acb602f933',
    messagingSenderId: '937453068234',
    projectId: 'finance-app-7ceb3',
    storageBucket: 'finance-app-7ceb3.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA05x1rgwqr2rtSVryJOX_4B1fqXrtS5wI',
    appId: '1:937453068234:ios:ef691de77e28acb602f933',
    messagingSenderId: '937453068234',
    projectId: 'finance-app-7ceb3',
    storageBucket: 'finance-app-7ceb3.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLUmnwyCdvrIsyOW7Kzh_976iwBXjLR0A',
    appId: '1:937453068234:web:419b1934795ebbeb02f933',
    messagingSenderId: '937453068234',
    projectId: 'finance-app-7ceb3',
    authDomain: 'finance-app-7ceb3.firebaseapp.com',
    storageBucket: 'finance-app-7ceb3.firebasestorage.app',
  );
}
